### PR TITLE
WIP BXMSDOC-8063: Removed procedure of creating DRL files in CodeReady

### PR DESCRIPTION
**Pull request by hmanwani-rh**
Removed the procedure of Creating and executing DRL rules in Red Hat CodeReady Studio, since CodeReady Studio is not incorporated. 

See JIRA: https://issues.redhat.com/browse/BXMSDOC-8063

Doc previews:
[Designing a decision service using DRL rules](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-8063-RHPAM/#drl-rules-other-con) in RHPAM

### CODE REVIEW

**Review by briandooley — APPROVED** [review]
LGTM

**Review by lucamolteni — APPROVED** [review]

**Review by jomarko — COMMENTED** [review]
Is there a reason we keep `AuthoringAssets/drl-rules-codeready-studio-create-proc.adoc` file?

- If **it is not used** on other places, then I think we should remove it as keeping it may be confusing for contributors.
- If **it is  used** on other places, such pieces of documentation are outdated and should be marked with some exclamation mark as obsolete, or at least mention in source, some comment referring the jira, where we will fix it.

**Review by jomarko — COMMENTED** [review]
@hmanwani-rh thank you for updates. I still think we should remove also the `AuthoringAssets/drl-rules-codeready-studio-create-proc.adoc` file.

To be clear what I mean, I created temporary branch with this commit https://github.com/jomarko/kie-docs/commit/b1e02450a6e8e88a0cb84fa924134b19df4f2409

**Comment by hmanwani-rh** [comment]
> @hmanwani-rh thank you for updates. I still think we should remove also the `AuthoringAssets/drl-rules-codeready-studio-create-proc.adoc` file.
> 
> To be clear what I mean, I created temporary branch with this commit [jomarko@b1e0245](https://github.com/jomarko/kie-docs/commit/b1e02450a6e8e88a0cb84fa924134b19df4f2409)

@jomarko I've removed the file. thanks

**Review by jomarko — APPROVED** [review]
Thank you @hmanwani-rh

**Pull request merged**
