### PR TITLE
WIP BXMSDOC-6220: Removed support for DMN 1.1 in DMN designer

### PR DESCRIPTION
**Pull request by hmanwani-rh**
See JIRA: https://issues.redhat.com/browse/BXMSDOC-6220

Added sentence to signify that DMN 1.1 is not supported in DMN editor. 

Doc previews:
[Designing a decision service using DMN models RHPAM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6220-RHPAM/#assembly-dmn-models)
[Designing a decision service using DMN models RHDM](http://file.pnq.redhat.com/~hmanwani/BXMSDOC-6220-RHDM/#assembly-dmn-models)

### CODE REVIEW

**Review by karreiro — COMMENTED** [review]
Thank you, @hmanwani-rh :-)

I've left a comment into BXMSDOC-6220, but this PR LGTM. I just would extend it a little bit to release notes. Let me know wdyt :-)

Thanks!

**Review by kaldesai — APPROVED** [review]
I reviewed your changes. Everything looks good to me. :)

**Comment by hmanwani-rh** [comment]
> Thank you, @hmanwani-rh :-)
> 
> I've left a comment into BXMSDOC-6220, but this PR LGTM. I just would extend it a little bit to release notes. Let me know wdyt :-)
> 
> Thanks!

I agree with adding a related entry in the release notes. I have linked BXMSDOC-6220 with the RN epic to make sure that the information will be added in the 7.9 release notes. 

Thanks for reviewing and sharing the feedback.

**Comment by hmanwani-rh** [comment]
> I reviewed your changes. Everything looks good to me. :)

Thanks @kaldesai

**Review by karreiro — APPROVED** [review]
Thank you, @hmanwani-rh.

**Review by jomarko — COMMENTED** [review]
I have one question. I see we have the same paragraph copied to three different files. Can't we eliminate this duplication by having one file and use some `include`  notation?

I think it would facilitate any further updates for given paragraph.

As said, just question not sure if its doable using `asciidoc` and structure we have in `kie-docs`

**Comment by hmanwani-rh** [comment]
> I have one question. I see we have the same paragraph copied to three different files. Can't we eliminate this duplication by having one file and use some `include` notation?
> 
> I think it would facilitate any further updates for given paragraph.
> 
> As said, just question not sure if its doable using `asciidoc` and structure we have in `kie-docs`

Thanks for reviewing the changes thoroughly. 
Regarding the repeated paragraph, we cannot add the include for a small paragraph, which is also a continuation paragraph with other sentences.

**Review by jomarko — APPROVED** [review]
@hmanwani-rh thank you for explanation and changes

**Pull request merged**
